// Generates the narration with ElevenLabs, one clip per shot, with
// character timestamps. Writes:
//   build/narration/<shot>.mp3   the voice
//   build/narration/<shot>.json  alignment + request fingerprint (cache)
//   build/narration.js           per-shot speech length, cue times, words
//   build/captions.srt           subtitles for the final video
// Re-running only re-requests shots whose text or voice settings changed.
//   node video/tools/narrate.mjs [--force] [shotId…]
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { BUILD, duration, eleven, fmtTime, loadProject, p } from './common.mjs';

const args = process.argv.slice(2);
const force = args.includes('--force');
const only = args.filter((a) => !a.startsWith('--'));

const { script, TL } = loadProject();
const dir = p('build/narration');
mkdirSync(dir, { recursive: true });

const spoken = script.shots.filter((s) => s.text).map((s) => ({ id: s.id, ...TL.parse(s.text) }));
const { voice } = script;
const result = {};

for (let i = 0; i < spoken.length; i++) {
  const s = spoken[i];
  const body = {
    text: s.clean,
    model_id: voice.model,
    voice_settings: voice.settings,
    // neighbouring lines keep the delivery continuous across clips
    previous_text: spoken[i - 1] ? spoken[i - 1].clean : undefined,
    next_text: spoken[i + 1] ? spoken[i + 1].clean : undefined,
  };
  // Cache on the line itself (not its neighbours), so editing one line
  // doesn't re-voice the lines around it.
  const key = createHash('sha1').update(JSON.stringify({ voice: voice.id, model: voice.model, settings: voice.settings, text: s.clean })).digest('hex');
  const jsonFile = `${dir}/${s.id}.json`;
  const mp3File = `${dir}/${s.id}.mp3`;
  let data = existsSync(jsonFile) ? JSON.parse(readFileSync(jsonFile, 'utf8')) : null;
  if (data && !data.sig && data.text === s.clean) data.sig = key; // cached before this scheme
  const stale = !data || data.sig !== key || !existsSync(mp3File);
  if (force && (!only.length || only.includes(s.id)) || (stale && (!only.length || only.includes(s.id)))) {
    process.stdout.write(`TTS ${s.id} (${s.clean.split(' ').length} words)… `);
    const res = await eleven(`/v1/text-to-speech/${voice.id}/with-timestamps`, body, { query: 'output_format=mp3_44100_192' });
    const json = await res.json();
    writeFileSync(mp3File, Buffer.from(json.audio_base64, 'base64'));
    data = { sig: key, text: s.clean, alignment: json.alignment };
    writeFileSync(jsonFile, JSON.stringify(data));
    console.log('done');
  } else if (stale) {
    console.warn(`! ${s.id} is out of date (skipped)`);
  }
  if (!data) continue;

  const al = data.alignment;
  const chars = al.characters.join('');
  if (chars !== s.clean) console.warn(`! ${s.id}: alignment text differs from script text`);
  const st = al.character_start_times_seconds;
  const en = al.character_end_times_seconds;
  const cues = {};
  for (const c of s.cues) cues[c.name] = +st[Math.min(c.index, st.length - 1)].toFixed(3);
  const words = [];
  const re = /\S+/g;
  let m;
  while ((m = re.exec(s.clean))) {
    const a = m.index, b = m.index + m[0].length - 1;
    words.push({ w: m[0], s: +st[a].toFixed(3), e: +en[Math.min(b, en.length - 1)].toFixed(3) });
  }
  const speech = +Math.max(...en).toFixed(3);
  result[s.id] = { file: `build/narration/${s.id}.mp3`, speech, audioDur: +duration(mp3File).toFixed(3), cues, words };
}

writeFileSync(p('build/narration.js'), `/* generated by tools/narrate.mjs */\nglobalThis.VHS_NARRATION = ${JSON.stringify(result)};\n`);

// ── report + captions ─────────────────────────────────
const { timeline } = loadProject();
let words = 0;
for (const s of timeline.shots) {
  if (s.clean) words += s.clean.split(' ').length;
  console.log(`${fmtTime(s.start).padStart(8)}  ${s.id.padEnd(11)} ${s.dur.toFixed(2).padStart(6)}s${s.speech ? `  speech ${s.speech.toFixed(2)}s` : ''}`);
}
console.log(`\n${words} words · total ${fmtTime(timeline.duration)}${timeline.estimated ? ' (some timings estimated)' : ''}`);

const srt = TL.captions(timeline);
const stamp = (t) => {
  const ms = Math.round(t * 1000);
  const h = Math.floor(ms / 3600000), mi = Math.floor(ms / 60000) % 60, se = Math.floor(ms / 1000) % 60;
  return `${String(h).padStart(2, '0')}:${String(mi).padStart(2, '0')}:${String(se).padStart(2, '0')},${String(ms % 1000).padStart(3, '0')}`;
};
writeFileSync(
  `${BUILD}/captions.srt`,
  srt.map((c, i) => `${i + 1}\n${stamp(c.a)} --> ${stamp(c.b)}\n${c.text}\n`).join('\n')
);
console.log(`captions: ${srt.length} lines → build/captions.srt`);
